#!/bin/bash

ssh 587aad4689f5cf759a0000a9@securityalarm-romif.rhcloud.com '/var/lib/openshift/587aad4689f5cf759a0000a9/app-root/runtime/repo/.openshift/action_hooks/stop'

scp target/*.war 587aad4689f5cf759a0000a9@securityalarm-romif.rhcloud.com:/var/lib/openshift/587aad4689f5cf759a0000a9/app-root/runtime/repo/bin/securityalarm.war

ssh 587aad4689f5cf759a0000a9@securityalarm-romif.rhcloud.com '/var/lib/openshift/587aad4689f5cf759a0000a9/app-root/runtime/repo/.openshift/action_hooks/start'
